### PR TITLE
Add coverage libraries and checks

### PR DESCRIPTION
**Pull request by vodennis**

### CODE REVIEW

**Comment by hergin** [comment]
You should update github actions file as well. Follow the assignment.

**Review by hergin — APPROVED** [review]

**Comment by hergin** [comment]
You merged without my approval?

**Comment by vodennis** [comment]
Sorry for not seeing that, I thought that since I received approval from you before and I had only removed Antone and added Riley as a reviewer, I didn't realize you needed to reapprove the pull since I hadn't made any changes since the last time you had approved my request (other than removing and adding a different reviewer).

**Comment by hergin** [comment]
It doesn't matter. If you can merge it without approval, you didn't update the settings in your repo. Problem.

**Comment by vodennis** [comment]
I have it set inside of Rules to only allow merges once approved by 2 reviewers. When you had approved my pull request beforehand it wouldn't let me merge since Antone hadn't approved it. But since he wasn't in class, I removed him and added Riley as a reviewer. Once Riley approved it, it allowed me to merge (maybe because you had already approved beforehand and I didn't make any changes to the code?)

**Comment by hergin** [comment]
image

This shouldn't happen. This is a new pull request, so it should still be approved. Check your settings again.

**Comment by vodennis** [comment]
Screenshot 2024-11-26 at 12 08 37 PM
Here's a screenshot of the settings, I have it set to 2 approvals so I'm not sure why this happened, could it be a bug?

**Comment by hergin** [comment]
Interesting. You didn't add any overrides or anything, right?

**Comment by vodennis** [comment]
Nope I didn't override anything

**Comment by hergin** [comment]
Ok. I will approve this for now. We can check later.

**Comment by vodennis** [comment]
Ok thanks, sorry for the confusion

**Comment by hergin** [comment]
It looks like you asked double reviews, for some reason, github paused over there. I removed myself now then my approved one showed up. No problem.

**Pull request merged**
